### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#100]
# Context
- Links start the respective flows
- Phone number is the phone number the user signed up with.
- Balance is displayed in a) the display currency and b) cUSD (the "real" balance).
- The profile icon is a javascript library called blockies that creates profile icons based on the blockchain address (see below).
- The blockies can only include the following color codes:

> #4840BB
> #282828
> #133FDB
> #B7004D

# Blockchain/Backend
- cUSD balance pulls the balance from the user's wallet (see valora wallet repo)
- Currency needs to be converted from cUSD to display currency with the currencylayer API: https://github.com/WakalaDAO/wakala-interface/issues/108

# Design
The circle in the top left corner is a placeholder for a blockie.
![image](https://user-images.githubusercontent.com/63787845/137919319-73596cfd-3ed7-4b37-82a9-8198e23fd74a.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1157%3A3272

# Blockies
See here:
- https://dacade.org/communities/celo-development-101/chapters/6bfd78c3-05b5-4074-921b-3375cdd74ede
- https://github.com/dacadeorg/celo-development-101/blob/main/code/celo101-code-chapter_3/3-2-the-html-of-your-project/index.html
- https://github.com/ethereum/blockies

How it looks like:
![image](https://user-images.githubusercontent.com/58551410/137898886-9228a41b-29f9-4ff9-8e73-7826eb3f721e.png)

![image](https://user-images.githubusercontent.com/58551410/137898085-8aa797be-4f55-4cd6-be3c-cb4e696958a9.png)

**Comment by steffenkrogmann** [comment]
@Chegemartinx please also add the color codes for the blockies in the issue description above.

**Comment by Chegemartinx** [comment]
A few issues: 

1. Remove the 'Sign out' option - We don't need it for wallet 
2. Align the 'Version number' with other content
3. Add a drop shadow on the white card- should be subtle
4. Is the 'Pin' option a placeholder?

**Comment by steffenkrogmann** [comment]
@sebastiaohns  though
6. The specific menu items are still wrong in the current build. But maybe that comes with the new PR and Zeel's pages...

**Comment by steffenkrogmann** [comment]
@sebastiaohns 
7. can the menu have rounded corners?
8. The space between the currency/balance card and "home" is missing. it is too close to each other.
9. The color of the divider lines between the menu items seems off and inconsistent.
10. The alignment of the circle + flag/number with the currency card is different. Flag etc is too far left compared to card....

@Chegemartinx

**Comment by steffenkrogmann** [comment]
@sebastiaohns 
Can you please update the menu to reflect the final menu? Not the intermediate placeholder one?

@Alphonce-Mutebi can you take on the blockies?
these will also be relevant for the feed/cards, rating screens, etc.
