### ISSUE TITLE
Home and Feed

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#101]
# Context
- Menu button opens draw/main menu.
- "Send" button starts the "Send money" flow.
- "Add/Withdraw" button starts the depos/withdraw request flow(s).
- The whole card (of a reqeust) is clickable. Not just the "view" button. Clicking it opens the detailed view of that request.

# Blockchain/Backend
- App needs to listen to these requests on the blockchain. Event listener. (directly blockchain).
- When any new user submits a new request to the blockchain, it should show on every user's phone.

# Wireframe

# Design

![image](https://user-images.githubusercontent.com/63787845/137936513-ed276c5a-2eda-4681-b7f3-eb43d955e58d.png)

 Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1185%3A2721

**Comment by steffenkrogmann** [comment]
see figma comments:
the scan icon feels kinda off, and there is one blockie/circle missing. pls update the screenshot here, too.

**Comment by Chegemartinx** [comment]
1. The buttons ( 'Send' and 'Add/Withdraw') are a bit big in the terms of height.
2. The current headline is in BOLD, should be REGULAR - 24px and body text should be REGULAR-16px

**Comment by steffenkrogmann** [comment]
@Chegemartinx @sebastiaohns 
4. is there a shadow missing at the send + add/withdraw bar?

**Comment by steffenkrogmann** [comment]
![Screenshot_20211101-155215.png](https://user-images.githubusercontent.com/58551410/139691441-2069e6ce-66d9-40d3-8794-73239477b7a3.png)

**Comment by Chegemartinx** [comment]
@steffenkrogmann , there is a subtle drop shadow on the card holding the 'send' and 'add/withdraw' button

**Comment by steffenkrogmann** [comment]
@Chegemartinx @sebastiaohns 

5. The gradient/color seems more intense in the design compared to my phone. What do you think?

6. The spacing between the cards is different and the height of the card feels too high compared to design. the page feels very crowded. Might be that the "view" button on the cards is too low and therefore makes the cards higher?

**Comment by Chegemartinx** [comment]
7. There is a white outline around each card.

**Comment by steffenkrogmann** [comment]
@Chegemartinx i dont know how exactly it is specified in the design. But the hamburger button feels very big on my phone. I compared it to other apps and they all tend to be significantly smaller.

**Comment by Chegemartinx** [comment]
@steffenkrogmann  I see where the issue is @sebastiaohns might have used a different icon from the one used in the design.

**Comment by steffenkrogmann** [comment]
@Chegemartinx so what do we do? and does the icon actually  affect the size? because it doesnt look thaaat different..

**Comment by Chegemartinx** [comment]
8. The view button is actually bigger be 69 by 25 px
9. The card size should be 328 by 94 px
10. Spacing between cards should be 32 px


@steffenkrogmann hopefully this will restrain the page from feeling to dense

**Comment by steffenkrogmann** [comment]
@sebastiaohns @onumengine pls integrate
