### ISSUE TITLE
SMS OTP

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#105]
# Context
- Page needs to display the phone number that the user used to sign up / login.
- 6 boxes for 6 digits to enter the OTP code.
- The page shows a countdown: "New code available in 29s" (seconds are counting down)
- After the countdown is over, the page displays a link "Send a new code".
- Clicking that link sends a new OTP code to your phone number.
- If the user is a new user (SIGN UP), he is sent to the ToC page: https://github.com/WakalaDAO/wakala-interface/issues/28
- If the user is an exiting user (LOGIN), he is sent directly to the home page of the app.
- Clicking "change" sends the user to the previous page where he can enter his phone number.
- Animated loader: https://reactnativeexample.com/a-customizable-animated-dots-component-for-use-in-react-native-apps/

# Blockchain/Backend
- Magic Link Integration: https://github.com/WakalaDAO/wakala-interface/issues/107 

# Design
![image](https://user-images.githubusercontent.com/63787845/136684584-8d31a793-d3e5-471d-8900-8dd3d695741d.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by Chegemartinx** [comment]
@steffenkrogmann from this option do you have a loader that you would prefer: https://www.npmjs.com/package/react-native-awesome-loading

**Comment by Chegemartinx** [comment]
@AbijahKaj couldn't find something cooler. Lets use this for now, https://reactnativeexample.com/a-customizable-animated-dots-component-for-use-in-react-native-apps/

**Comment by steffenkrogmann** [comment]
Closing this issue because we don't need it. A magic overlay will handle that directly.

See the video that @Alphonce-Mutebi shared.

@Chegemartinx @AbijahKaj 

https://discord.com/channels/@me/902122495220535327/906474038849843233
