### ISSUE TITLE
Confirm your request (request  cUSD to MPESA)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#126]
# Context
- (i) next to fees opens pop up
- Link in pop up tbd, see: https://github.com/WakalaDAO/wakala-interface/issues/97
- "Swipe to confirm" shares the deposit request with the agent network.
- "Swip to confirm" also triggers the "Request Shared" push up. https://github.com/WakalaDAO/wakala-interface/issues/86

# Blockchain
- The request happens on chain.
- It is submitted to the Wakala smart contract: https://github.com/WakalaDAO/wakala-interface/issues/106

# Design
![image](https://user-images.githubusercontent.com/58551410/138886905-cfeb4dee-33d1-499b-800d-d0e516f6e39f.png)

![image](https://user-images.githubusercontent.com/58551410/138887258-14937497-c552-4770-949b-e05e598f527f.png)

Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
![image](https://user-images.githubusercontent.com/58551410/142332634-fae3c284-8094-49c0-9897-18611a1696ff.png)

@sebastiaohns the amounts are not in the same line as the text, they are too low.
And please add the i icon overlay with the info and link. (see figma)
