### ISSUE TITLE
Rating (request cUSD to  M-PESA)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#128]
# Context
- User can rate 1-5
- When the user selects an emoji, it changes the appearance.
- The profile itself (the ratings etc) are not clickable.
- Only way to get out of this page is to submit a rating.

# UI Reusability
- Sam as: https://github.com/WakalaDAO/wakala-interface/issues/90

# Blockchain
- Ratings will happen on chain.
- Integrated with the Wakala Smart contract: https://github.com/WakalaDAO/wakala-interface/issues/106
- We will likely use the Karma protocol for on chain ratings (another project on Celo). Related issue: https://github.com/WakalaDAO/wakala-interface/issues/112

# Design

![image](https://user-images.githubusercontent.com/63787845/136775773-81db979f-8485-4c71-9b66-bee4215e27e0.png)
Design: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
please remove the back arrow in the top left corner on all rating screens @sebastiaohns 
there is nothing to go back to

(the figma decisions are inconsitent there, sorry. some show it, some dont.)

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi please integrate with Karma and blockies.

(there are 4 flows in Figma/github with ratings. not sure how that differentiation affects you, so i assign all those issues to you).
