### ISSUE TITLE
User confirms he received M-PESA payment (request cUSD to M-PESA)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#130]
# Context
-This page shows Mpesa details (Phone number) and amount to receive MPESA
-I swipe to confirm I have sent the M-PESA payment (outside the app).

# Blockchain
- The confimation happens on chain, because it is needed to release money from escrow.

# Design
![image](https://user-images.githubusercontent.com/58551410/138887985-ea2494e5-9f29-4d81-88d1-2ff7767324b4.png)

https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1501%3A7805

**Comment by steffenkrogmann** [comment]
@sebastiaohns 

Please remove the back arrow in the upper left corner
(same as issue https://github.com/WakalaDAO/wakala-interface/issues/87 )


Is the phone number hard coded?
That would have to be integrated then
