### ISSUE TITLE
Accept Request (fulfill cUSD to M-PESA )

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#131]
# Context
- Swiping accepts the request and triggers the confirmation push-up overlay. 

# Blockchain
- This confirmation happens on chain.

# Design
![image](https://user-images.githubusercontent.com/63787845/138098586-a1923b08-045d-43ab-b43f-e10facc34a5f.png)

Link; https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1298%3A4422

**Comment by steffenkrogmann** [comment]
@sebastiaohns the amounts and text (total you receive...) are not in line. same issue as in the request flows.
and the info overlay icon is missing.(see figma)
