### ISSUE TITLE
Transaction successful (fulfill cUSD to MPESA)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#134]
# Context
 
This page is triggered after the agent confirmed that he received the M-PESA payment on the previous page.
- Clicking "got it" sends the user to the "Rating" page.
- On the user side, this trigger is on chain. For the agent (on this page) the trigger is local, because the agent himself sends the confirmation.

- Confetti animation for last page:
https://reactnativeexample.com/react-native-component-to-show-confetti/ 
- Color codes for confetti animation:
> #4840BB
> #282828
> #133FDB
> #B7004D

# Design
![Transaction Successful!](https://user-images.githubusercontent.com/63787845/138945542-0b9f571b-198a-4e5e-a94c-fb1d1275a5ae.png)

link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1506%3A3311

**Comment by steffenkrogmann** [comment]
@Chegemartinx we cannot have the little escrow text here. the transaction is already complete. Otherwise it would not be a success ;-)

Please lets just have the "transaction successful" centered. on both of these screens.
See also: https://github.com/WakalaDAO/wakala-interface/issues/89

**Comment by Chegemartinx** [comment]
@steffenkrogmann I feel like centering will make it too low/close to the button : Do you prefer this one?
![image](https://user-images.githubusercontent.com/63787845/138088298-9ac0c95b-6bdb-4aa4-abce-e7f85dd616cf.png)
