### ISSUE TITLE
Rating (Fulfill cUSD to MPESA)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#135]
# Context
- User can rate 1-5
- When the user selects an emoji, it changes the appearance.
- The profile itself (the ratings etc) are not clickable.
- Only way to get out of this page is to submit a rating.

# UI Reusability
- All the same as: https://github.com/WakalaDAO/wakala-interface/issues/90

# Blockchain
- Ratings will happen on chain.
- Integrated with the Wakala Smart contract: https://github.com/WakalaDAO/wakala-interface/issues/106
- We will likely use the Karma protocol for on chain ratings (another project on Celo). Related issue: https://github.com/WakalaDAO/wakala-interface/issues/112

Design
![image](https://user-images.githubusercontent.com/63787845/137781291-87f81961-8d90-4f5c-a5fd-abddae0f323e.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi pls integrate with karma and blockies
