### ISSUE TITLE
Error: Request Mpesa to cUSD (Deposit)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#196]
# Context

Every time when a user tries to interact with the smart contract, there is a possibility that it doesn't work sometimes. 
We need to communicate to the user that they are aware of the error so that they can try again. 

Clicking "Try Again" here would then not send you home, but simply put you on the same page where you can swipe/confirm again.

# Design

![image](https://user-images.githubusercontent.com/63787845/141973750-728165d9-b823-4665-b23b-b2cfabc61fe0.png)

Figma: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2524%3A1825

**Comment by steffenkrogmann** [comment]
@sebastiaohns this is the UI in case of a connection error.

btw. do you need a loader? 

cc @Chegemartinx
