### ISSUE TITLE
Error: Rating (request M-PESA to cUSD)

### ISSUE THREAD

**Issue by Chegemartinx** [WakalaDAO/wakala-interface#198]
# Context
Every time when a user tries to rate a transaction they will interact with the smart contract, there is a possibility that it doesn't work sometimes. 
We need to communicate to the user that they are aware of the error so that they can try again. 

Clicking "Try Again" here would then not send you home, but simply put you on the same page where you can swipe/confirm/Submit again.

# Design
![image](https://user-images.githubusercontent.com/63787845/141975251-47f5c4ae-c258-4eee-a176-f9d6b1c3cd92.png)

Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2530%3A2666

**Comment by steffenkrogmann** [comment]
@sebastiaohns this is the UI in case of a connection error.
