### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#22]
# Context
- Splash screen loads every time I open the app.
- Splash screen disappears (app moved to next page) automatically, no user action needed.

# Design

![Splash screen](https://user-images.githubusercontent.com/63787845/139886250-d50faf0e-c6ed-4f5a-b911-a7e2d5e8ec37.png)

Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2088%3A2027

**Comment by steffenkrogmann** [comment]
Ready for design

**Comment by steffenkrogmann** [comment]
splash screen is ready for development @AbijahKaj

**Comment by steffenkrogmann** [comment]
@AbijahKaj please add splash screen.

**Comment by steffenkrogmann** [comment]
https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2683%3A2476

**Comment by AbijahKaj** [comment]
@Chegemartinx I'm making the splash screen, for that I'll need an image of 1242 pixels wide and 2436 pixels tall, containing the logo. You can check this link for reference https://www.figma.com/file/ddc0glVeILssZl0Dcn1lSS/App-Icon-%26-Splash?node-id=0%3A1

**Comment by Chegemartinx** [comment]
@AbijahKaj here it is: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2711%3A2437

**Comment by AbijahKaj** [comment]
![IMG_5B8A2895A34A-1](https://user-images@Chegemartinx githubusercontent.com/34766858/142740880-28786b61-c6f2-470b-ad6c-e21605fd05bc.jpeg)

@Chegemartinx there're some dots in the Splash Screen you provided (they're very small but noticeable).

**Comment by steffenkrogmann** [comment]
reassigned to @Chegemartinx

**Comment by Chegemartinx** [comment]
@AbijahKaj dots have been removed, follow this link please to find the updated screens: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2711%3A2437

**Comment by AbijahKaj** [comment]
Done! Reassigning to @steffenkrogmann

**Comment by steffenkrogmann** [comment]
closing this, but there is the separate bug about the "jumping" splash screen.
