### ISSUE TITLE
After closing the app and reopening again, cant move the onboarding screens forward

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#226]
I opened the app.
Then i closed it by moving BACK (with the phone button).
When i opened the app again and clicked on the button at the bottom, it is stuck (i can swipe though).

**Video:**
https://user-images.githubusercontent.com/58551410/142741711-9288bd8e-7389-472f-96a2-ff7d49feb47e.mp4

**Comment by AbijahKaj** [comment]
That's not a bug! That's how the app is supposed to work ! I you wanna see the onboarding process again, just delete cache/data from your phone settings or Uninstall then install the app.

**Comment by steffenkrogmann** [comment]
Thank you @AbijahKaj 

I am testing right now and throwing a few things at you. If you are not the right person , or we run into workload problems, we can always reassign.
