### ISSUE TITLE
Magic sign up takes a few seconds and needs to show the user that something is happening.

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#231]
Hey @Alphonce-Mutebi and @Chegemartinx 

After I enter my phone number, it takes about 5 seconds until the magic screen shows. 
But i dont know as a user if it actually worked, so i click submit like 5 times....

We need to show that to the user.
A loader?
or the magic web demo kinda greys out the button.

Magic:
https://magic-celo.vercel.app/login

Screenrecording:
https://user-images.githubusercontent.com/58551410/142742541-d9500dbf-fc04-44a6-8443-b6317cbf8a43.mp4

**Comment by Chegemartinx** [comment]
@Alphonce-Mutebi: My thoughts, we probably do it in two alternatives. One, grey out the button once a user makes a request. Two, would it be possible for us to have an empty draw screen as seen here ([Link](https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2740%3A2503) that is the same size as the magic draw menu or can be a pop-up but with a loader, disappears once the magic link pops out.

**Comment by steffenkrogmann** [comment]
i like it.

@Chegemartinx can/should you do a quick design of the greyed out button as well?

**Comment by Chegemartinx** [comment]
@Alphonce-Mutebi design update for a greyed out button, let me know what you think: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=2750%3A2429  cc @steffenkrogmann
