### ISSUE TITLE
Sign up and Log in Page

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#27]
# Context
- User has 3 options: to create a new account via phone number, to login via phone number, or to restore an existing account (wallet).
- Phone number needs to validate for international format (e.g. +254...)
- Clicking the "back" arrow gets the user back to the last info swipe screen 4.
- Ater the user enter his phone number (does't matter whether he is a first time user or not, he is sent to the SMS OTP page. https://github.com/WakalaDAO/wakala-interface/issues/105
- Clicking "restore existing account" sends user to the restore existing wallet flow.  https://github.com/WakalaDAO/wakala-interface/issues/36

# Blockchain/Backend
- Magic Link integration: https://github.com/WakalaDAO/wakala-interface/issues/107

# Wireframe

# Design

![image](https://user-images.githubusercontent.com/63787845/136684604-07da04a1-a873-4f9f-943d-7763602603cd.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1139%3A1867

**Comment by steffenkrogmann** [comment]
@Chegemartinx accept button is missing

**Comment by steffenkrogmann** [comment]
@Chegemartinx ready for design

**Comment by Chegemartinx** [comment]
1. Make the text to be 3 Rows similar to the design, to cover the white space below the text
2. The 'CTA' next to the phone number should have one color #4840BB and not a gradient.
3. When I click to type the phone number, the button squeezes the field upwards (see screenshot). Is there a way we can maintain the same margin space similar to what it looks like before typing? That would be ideal.
![image](https://user-images.githubusercontent.com/63787845/139664997-945135d1-2352-4a10-bbf3-0367cf273a3a.png)

**Comment by steffenkrogmann** [comment]
@Chegemartinx @AbijahKaj this is

**Comment by steffenkrogmann** [comment]
@AbijahKaj please notice the small design change (button text)
