### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#28]
# Context
- Terms and conditions are hardcoded.
- Text tbd-. See here. https://github.com/WakalaDAO/wakala-interface/issues/38
- Use existing dummy text for now.
- Text will also contain a link to the website wakala.xyz/terms for more info.
- Clicking accept gets the user to the next page.
- We do not record the data/user accepting anywhere.

# Design
![image](https://user-images.githubusercontent.com/63787845/136684682-5b81ca84-97c0-40aa-8e46-f61b95cea369.png)
https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1139%3A1901

**Comment by steffenkrogmann** [comment]
@Chegemartinx accept button is missing

**Comment by Chegemartinx** [comment]
1. The button is way below the screen,its hidden (see screenshot)
![image](https://user-images.githubusercontent.com/63787845/139668898-e981834e-ae1c-4dc3-a90e-5779dd3fb76c.png)

**Comment by Chegemartinx** [comment]
@steffenkrogmann do we need a back button on this page? Where should it take you?

**Comment by Chegemartinx** [comment]
@AbijahKaj @steffenkrogmann we keep the back button and takes you back to login page, where you either sign up, or restore account.

**Comment by steffenkrogmann** [comment]
yep

**Comment by steffenkrogmann** [comment]
@AbijahKaj pls update spacing
