### ISSUE TITLE
Restore Existing Wallet: Enter Recovery Phrase

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#36]
# Context
- User is asked to enter his recovery phrase.
- User confirms by clicking "Restore" (triggers the verficiation process and moves used to next page).
- User can go back to https://github.com/WakalaDAO/wakala-interface/issues/27 by clicking the back arrow.
- correct recovery phrase shows success "push-up"
- wrong recovery phrase shows error message

# Design
![image](https://user-images.githubusercontent.com/63787845/136685268-8380c850-de88-42eb-bea5-93bd6c3264b9.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1139%3A2170

Success and error confirmation
![image](https://user-images.githubusercontent.com/63787845/137917697-8e766daa-277c-407a-ab4a-d7b59ca78c6c.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
@Chegemartinx remove the steps in the top right, see figma comment

**Comment by Chegemartinx** [comment]
@steffenkrogmann @AbijahKaj closing this issue
