### ISSUE TITLE
Restore Existing Wallet: Verify Recovery Phrase

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#37]
# Context
- page shows a loader in the Recovery phrase box that indicates verification.
- After recovery phrase is veryfied, the app moves to the https://github.com/WakalaDAO/wakala-interface/issues/28 page and follows the normal onboaring/phone number verification flow.

# UI Reusability
- https://github.com/WakalaDAO/wakala-interface/issues/36

# Design
![image](https://user-images.githubusercontent.com/63787845/136685288-288895aa-b43b-4d9f-b975-74ed19630589.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1141%3A2184

Success and error confirmation
![image](https://user-images.githubusercontent.com/63787845/137917697-8e766daa-277c-407a-ab4a-d7b59ca78c6c.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
@Chegemartinx we need an error message somehow for when the phrase is wrong.

**Comment by Chegemartinx** [comment]
@steffenkrogmann @AbijahKaj closing this issue too
