### ISSUE TITLE
View Recovery Phrase

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#76]
# Context
- App asks user to enter his PIN before it then redirects to the Recovery Phrase page.
- Page that shows the Recovery Phrase of the wallet that is logged in.
- Clicking "back arrow" gets the user back to the settings page.
- Page CAN NOT be screenshotted (users need to manually write the key down).
- Clicking "OK" sends the user to Home.

# Magic Link
- In order to see the recovery phrase, Magic needs to set something up.
- From email exchange: 
"If a user wants to see their private key, we'll need to setup a URL for your app where users can login to view it - see https://reveal.magic.link/niftys as an example of this."

# Design

![image](https://user-images.githubusercontent.com/63787845/136767751-26d6b156-286c-4eb6-b96f-62e9997a994d.png)
Link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3

**Comment by steffenkrogmann** [comment]
@Chegemartinx ready for design

**Comment by Kapersky1337** [comment]
Design implemented for this page.

**Comment by steffenkrogmann** [comment]
@Chegemartinx @Kapersky1337 closing this, because it is redundant
