### ISSUE TITLE
Confirm your request  (request M-PESA to cUSD)

### ISSUE THREAD

**Issue by steffenkrogmann** [WakalaDAO/wakala-interface#85]
# Context
- (i) next to fees opens pop up
- Link in pop up tbd, see: https://github.com/WakalaDAO/wakala-interface/issues/97
- "Swipe to confirm" shares the deposit request with the agent network.
- "Swip to confirm" also triggers the "Request Shared" push up. https://github.com/WakalaDAO/wakala-interface/issues/86

# Blockchain
- The request happens on chain.
- It is submitted to the Wakala smart contract: https://github.com/WakalaDAO/wakala-interface/issues/106

# Design
![image](https://user-images.githubusercontent.com/63787845/136776607-c85c0d8c-4be5-4c87-b698-e676f6333702.png)
link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1299%3A4510

**Comment by steffenkrogmann** [comment]
@Chegemartinx please add wireframe for page and pop up.

**Comment by Chegemartinx** [comment]
@steffenkrogmann added

**Comment by steffenkrogmann** [comment]
@Chegemartinx ready for design

**Comment by steffenkrogmann** [comment]
![image](https://user-images.githubusercontent.com/58551410/142332634-fae3c284-8094-49c0-9897-18611a1696ff.png)

@sebastiaohns the amounts are not in the same line as the text, they are too low.
And please add the i icon overlay with the info and link. (see figma)
